version: '3.1'

services:
  dbmongo:
    image: mongo:4.2
    container_name: dbmongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    expose:
      - '27017'
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
  orders:
    build:
      context: ./orders-service
    volumes:
      - ./:/code
    command: npm run start
    ports:
      - '3000:3000'
    image: orders
    container_name: orders
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=dbmongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    depends_on:
      - dbmongo
volumes:
  mongodb:
